### ISSUE TITLE
如果, 要從 <script> 跳轉到 </script> 或是 要從 <div> 跳轉到 </div>有沒有什麼快速鍵?

### ISSUE THREAD

**Issue by leo19790301** [MicrosoftDocs/visualstudio-docs.zh-tw#100]
如果, 要從 <script> 跳轉到 </script> 或是 要從 <div> 跳轉到 </div>有沒有什麼快速鍵?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [預設鍵盤快速鍵 - Visual Studio](https://docs.microsoft.com/zh-tw/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @leo19790301
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #5418](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5418) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
您好，@leo19790301，  

非常感謝您的貢獻。您的意見反應與原始文件相關。  

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/visualstudio-docs/issues/5418。  

我們由衷感謝您對文章的貢獻。   

順頌時祺  
Microsoft DOCS 國際小組
