### ISSUE TITLE
import numpy fail

### ISSUE THREAD

**Issue by marcolin1215** [MicrosoftDocs/visualstudio-docs.zh-tw#11]
Hi Sir,
我follow 文件的教學順利將MNIST_demo 的training job submit 到我create 的DSVM.
但是,卻執行失敗. 原因是import numpy fail. 但是我SSH 進去VM查詢,卻發現numpy 是有預先安裝在 DSVM裡. 然後我直接在command line 執行 Python mnist.py, 是可以執行,不會有import fail 的問題.
請問這是什麼問題?

Thanks

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4ff24ba6-41f5-f6a5-949a-54d8e4df7e0e
* Version Independent ID: bb68990d-084f-be46-8c0a-6c9d34a060ac
* Content: [在雲端中執行 TensorFlow 模型](https://docs.microsoft.com/zh-tw/visualstudio/ai/tensorflow-vm)
* Content Source: [docs/ai/tensorflow-vm.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/ai/tensorflow-vm.md)
* Service: **multiple**
* Product: **visual-studio-dev15**
* GitHub Login: @lisawong19
* Microsoft Alias: **liwong**

**Comment by marcolin1215** [comment]
Hi Sir,
我開了一個DLVM(NC6), 一樣在Visual Studio submit job 到我的DLVM. 我看到submit成功.
但還是執行失敗. 原因一樣是import numpy error. 我一樣SSH進去查看, numpy 是有裝的.
一樣用command 執行 python mnist.py 是可以執行的(不會出現import error)
所以感覺上是Visual studio 送出去的job , 才看到這個問題

**Comment by gosali** [comment]
您好，@marcolin1215，

非常感謝您的貢獻。我們的小組只會針對文件相關的意見反應提出回應。
請使用 DOCS 頁面底部的 [提供產品意見反應] 按鈕來記錄您的產品意見反應。
若您在文件方面有任何意見反應，請隨意透過此管道加以記錄。
我們由衷感謝您對文章的貢獻。
順頌時祺
CC @nokura 

Microsoft DOCS 國際小組
