### ISSUE TITLE
將ASP.NET應用程式部署到使用 Visual Studio 的本機資料夾，無法執行問題

### ISSUE THREAD

**Issue by yangchenshin77** [MicrosoftDocs/visualstudio-docs.zh-tw#23]
我建置了一個ASP.NET應用程式，照這篇文檔的方法操作，發佈至本機資料夾。
後將這網站放至IIS運行，卻回報此錯誤：
![okcarweb-1](https://user-images.githubusercontent.com/38133356/46660893-9e18a080-cbea-11e8-83e3-738f739412eb.jpg)
請問如何解決?

---
    (我知道我不該在這裡問無關文檔的問題，但依照文檔操作完之後出現了問題，無可奈何之下便提出了)
---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 7acfded6-bb6d-cf61-0cf0-a4457bbff059
* Version Independent ID: c1974839-4571-e19c-e484-a98e4121e17c
* Content: [部署到本機資料夾 - Visual Studio](https://docs.microsoft.com/zh-tw/visualstudio/deployment/quickstart-deploy-to-local-folder?view=vs-2017)
* Content Source: [docs/deployment/quickstart-deploy-to-local-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/deployment/quickstart-deploy-to-local-folder.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by yangchenshin77** [comment]
問題已解決！

因為網站不是放在根目錄，而`bin`資料夾必須要放至網站跟目錄下，才可正常運行。

建議可將此問題加入文檔。

**Comment by LisandroSu** [comment]
您好 @yangchenshin77 

 謝謝您的寶貴意見。 

 順頌時祺 
Microsoft DOCS 國際小組
