### ISSUE TITLE
離線安裝仍出現下載失敗的解決辦法

### ISSUE THREAD

**Issue by dannypc1628** [MicrosoftDocs/visualstudio-docs.zh-tw#37]
在vs2017layout中尋找錯誤訊息中，需要下載的套件名稱
如果有該套件存在，可能因為套件名稱後面有漏字，導致安裝程式以為無該套件
補上闕漏的字就可以正常安裝
詳細 https://dannyliu.me/fix-visual-studio-2017-offline-install-error/

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [建立 Visual Studio 的離線安裝 - Visual Studio](https://docs.microsoft.com/zh-tw/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs #1818](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1818) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
您好，@dannypc1628， 
非常感謝您的貢獻。您的意見反應與原始文件相關。 
因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - XXX。 
我們由衷感謝您對文章的貢獻。  
順頌時祺 
Microsoft DOCS 國際小組
