### ISSUE TITLE
In Visual Studio 2019, I tried to test console.log using node.js console app. But I can not find the [JavaScript console window].

### ISSUE THREAD

**Issue by boltnut** [MicrosoftDocs/visualstudio-docs.zh-tw#74]
[請在此輸入您的意見] 
請問在 Visual Studio 2019 寫一簡單node.js console app 測試程式, 嘗試 console.log() 功能。官網所謂`[JavaScript 主控台]` 視窗, 卻遍尋不找?
In Visual Studio 2019, I tried to test console.log using node.js console app. But I can not find the [JavaScript console window].

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 1dd84513-cff5-84b5-40fa-4db1399fddcb
* Version Independent ID: d677568a-4b8d-c45d-a4a8-ab6309bb95d1
* Content: [JavaScript 主控台命令 - Visual Studio](https://docs.microsoft.com/zh-tw/visualstudio/debugger/javascript-console-commands?view=vs-2019)
* Content Source: [docs/debugger/javascript-console-commands.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docs/debugger/javascript-console-commands.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@boltnut Hi, did you create the app using a Node.js template installed with the Node.js app development workload? The VS workload for Node.js is required. Also, the console is only available while debugging, so set a breakpoint in your code, hit the breakpoint, and then open the console if it is closed.
